// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quan_li_app.Models;

#nullable disable

namespace quanliapp.Migrations
{
    [DbContext(typeof(SystemContext))]
    [Migration("20231129165930_taoDBMau-3")]
    partial class taoDBMau3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("quan_li_app.Models.SysMenu", b =>
                {
                    b.Property<string>("menuid")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar")
                        .HasColumnName("menuid");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<bool>("isParent")
                        .HasColumnType("bit")
                        .HasColumnName("isParent");

                    b.Property<string>("menuIDParent")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar")
                        .HasColumnName("menuIDParent");

                    b.Property<string>("moduleApp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("name");

                    b.HasKey("menuid");

                    b.ToTable("SysMenu", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
