// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quan_li_app.Models;

#nullable disable

namespace quan_li_app.Migrations.System
{
    [DbContext(typeof(SystemContext))]
    [Migration("20231204064037_taoDBMau-9-sysModule")]
    partial class taoDBMau9sysModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("quan_li_app.Models.SystemDB.AppModule", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("dateEnable")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("enabled")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("AppModels", (string)null);
                });

            modelBuilder.Entity("quan_li_app.Models.SystemDB.SysMenu", b =>
                {
                    b.Property<string>("menuid")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar")
                        .HasColumnName("menuid");

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<bool?>("defaultActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("isParent")
                        .HasColumnType("bit")
                        .HasColumnName("isParent");

                    b.Property<string>("menuIDParent")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar")
                        .HasColumnName("menuIDParent");

                    b.Property<string>("moduleApp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("name");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("menuid");

                    b.ToTable("SysMenu", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
