// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quan_li_app.Models;

#nullable disable

namespace quanliapp.Migrations.Data
{
    [DbContext(typeof(DataContext))]
    [Migration("20240630202314_30062024_create_catalog")]
    partial class _30062024_create_catalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.CategoryCommonModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("group_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("number_order")
                        .HasColumnType("int");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("CategoryCommon", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.DocumentManagement", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeLogTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isClose")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("isCompanyCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("lenCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(16);

                    b.Property<string>("module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("primaryKeyTable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("DocumentManagement", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.LanguageModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameCN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameVN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Language", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.Movie.MasterData.MovieGenresModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("genres_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_parent")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("MovieGenres", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.Movie.MasterData.MovieModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("duration")
                        .HasColumnType("float");

                    b.Property<string>("genres_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("language_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("movie_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("national_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("release_year")
                        .HasColumnType("int");

                    b.Property<string>("thumbnail_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trailer_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Movie", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.Movie.MovieReactionToMovieModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("movie_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reaction_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("MovieReactionToMovie", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.Movie.Transaction.MovieCommentModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("id_parent")
                        .HasColumnType("bit");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("movie_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("movie_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parent_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("MovieComment", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.Movie.Transaction.MovieFavoritesModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("movie_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("movie_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("movie_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("movie_thumbnail_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("movie_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("MovieFavorites", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.Movie.Transaction.MovieReactionToCommentModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("comment_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("reaction_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("MovieReactionToComment", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.Movie.Transaction.MovieReivewModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("movie_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("rating")
                        .HasColumnType("float");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("MovieReivew", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.Movie.Transaction.MovieWatchHistoryModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("movie_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("movie_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("movie_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("movie_thumbnail_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("movie_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("time_view")
                        .HasColumnType("float");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("MovieWatchHistory", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.National", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zip_code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("National", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.QuanLiNhanSu.DanhMuc.DepartmentModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_delete")
                        .HasColumnType("bit");

                    b.Property<int?>("level")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.QuanLiNhanSu.DanhMuc.PositionModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Position", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.QuanLiNhanSu.DanhMuc.StatusEmployeeModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("StatusEmployee", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.QuanLiNhanSu.DanhMuc.TypeEmployeeModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TypeEmployee", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.QuanLiNhanSu.DanhMuc.TypeWorkModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TypeWork", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.UploadFileModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("col_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("enabled")
                        .HasColumnType("bit");

                    b.Property<string>("file_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("file_path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("file_size")
                        .HasColumnType("float");

                    b.Property<string>("file_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("table_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("UploadFile", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.DataDB.User.EmployeeModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BHXH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("avatar16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("avatar32")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("avatar64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("department_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ethnicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("interests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("maritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("modifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("position_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_employee_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_work_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("quan_li_app.Models.Common.SysModule", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("code_Render_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("enabled")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("SysModule", (string)null);
                });

            modelBuilder.Entity("quan_li_app.Models.Common.SysPermission", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("codeCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("level")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("order_number")
                        .HasColumnType("int");

                    b.HasKey("code");

                    b.ToTable("SysPermission", (string)null);
                });

            modelBuilder.Entity("quan_li_app.Models.Common.SysStatus", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("accept_login")
                        .HasColumnType("bit");

                    b.Property<string>("appModule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("enable")
                        .HasColumnType("bit");

                    b.Property<string>("module")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("order_numer")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("SysStatus", (string)null);
                });

            modelBuilder.Entity("quan_li_app.Models.Common.SysTypeAccount", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("SysTypeAccount", (string)null);
                });

            modelBuilder.Entity("quan_li_app.Models.DataDB.Account", b =>
                {
                    b.Property<string>("account")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("codePermision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("last_enter")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("lock_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_account")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("account");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("quan_li_app.Models.DataDB.Company", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<string>("address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adminCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("delete_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_delete")
                        .HasColumnType("bit");

                    b.Property<int?>("left_company")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("right_company")
                        .HasColumnType("int");

                    b.Property<DateTime?>("update_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Company", (string)null);
                });

            modelBuilder.Entity("quan_li_app.Models.DataDB.MenuPermissions", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("menuid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modify")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("MenuPermissions", (string)null);
                });

            modelBuilder.Entity("quan_li_app.Models.DataDB.QuanLiNhanSu.CurrentJobPosition", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdUserInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currentProjects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("departmentOrTeam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("goalsAndDevelopment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modyfiBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("positionAndLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("workSchedule")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("CurrentJobPosition", (string)null);
                });

            modelBuilder.Entity("quan_li_app.Models.DataDB.QuanLiNhanSu.SalaryAndBenefits", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdUserInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("allowancesAndAids")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("allowancesAndAids1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("allowancesAndAids2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("allowancesAndAids3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("allowancesAndAidsAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("allowancesAndAidsAmount1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("allowancesAndAidsAmount2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("allowancesAndAidsAmount3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("benefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("compensationPackage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("compensationPackage1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("compensationPackage2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("compensationPackage3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("compensationPackageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("compensationPackageAmount1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("compensationPackageAmount2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("compensationPackageAmount3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("insuranceCoverage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modyfiBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("wagesAndPerks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("SalaryAndBenefits", (string)null);
                });

            modelBuilder.Entity("quan_li_app.Models.DataDB.QuanLiNhanSu.WorkHistory", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdUserInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("achievementSkills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyAndPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("jobdeScription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modyfiBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reasonForChange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timeWorked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("workHistoryEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("workHistoryStart")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("WorkHistory", (string)null);
                });

            modelBuilder.Entity("quan_li_app.Models.DataDB.TOKEN", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("browser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("browser_version")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("connectionSignalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("device")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ip_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("is_android")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_connecting")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_desktop")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_ios")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_mobile")
                        .HasColumnType("bit");

                    b.Property<bool?>("is_tablet")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("last_date_connect")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("latitude")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal?>("longitude")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("orientation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("os")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("os_version")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_device")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Token", (string)null);
                });

            modelBuilder.Entity("quan_li_app.Models.DataDB.UserData.UserInfo", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BHXH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("avatar16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("avatar32")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("avatar64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("ethnicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("interests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("modifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("UserInfomation", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
