// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quan_li_app.Models;

#nullable disable

namespace quan_li_app.Migrations.System
{
    [DbContext(typeof(SystemContext))]
    [Migration("20240227082839_27022024_create_module_action")]
    partial class _27022024_create_module_action
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL_QUANLI.Models.SystemDB.SysAction.SysAction", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("actionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("backgroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isClocked")
                        .HasColumnType("bit");

                    b.Property<bool?>("isDisable")
                        .HasColumnType("bit");

                    b.Property<string>("nameOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameVn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url_4")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("SysAction", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.SystemDB.SysAction.SysDropDownAction", b =>
                {
                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("orderNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SysDropDownAction", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.SystemDB.SysAction.SysGroupAction", b =>
                {
                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("orderNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SysGroupAction", (string)null);
                });

            modelBuilder.Entity("quan_li_app.Models.SystemDB.AppModule", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("dateEnable")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("enabled")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("AppModels", (string)null);
                });

            modelBuilder.Entity("quan_li_app.Models.SystemDB.SysMenu", b =>
                {
                    b.Property<string>("menuid")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar")
                        .HasColumnName("menuid");

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<bool?>("defaultActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("isParent")
                        .HasColumnType("bit")
                        .HasColumnName("isParent");

                    b.Property<string>("menuIDParent")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar")
                        .HasColumnName("menuIDParent");

                    b.Property<string>("moduleApp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("name");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("menuid");

                    b.ToTable("SysMenu", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
