// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quan_li_app.Models;

#nullable disable

namespace quan_li_app.Migrations.System
{
    [DbContext(typeof(SystemContext))]
    [Migration("20240514180927_14052024_update_table_col")]
    partial class _14052024_update_table_col
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL_QUANLI.Models.SystemDB.SysAction.SysAction", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("backgroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isDisable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("nameOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameVn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url_4")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("SysAction", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.SystemDB.SysAction.SysDropDownAction", b =>
                {
                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isClocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("orderNo")
                        .IsRequired()
                        .HasColumnType("int");

                    b.ToTable("SysDropDownAction", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.SystemDB.SysAction.SysGroupAction", b =>
                {
                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codeAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isClocked")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("isDropDown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("orderNo")
                        .IsRequired()
                        .HasColumnType("int");

                    b.ToTable("SysGroupAction", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.SystemDB.SysGenRowTable", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<string>("alignment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("allowEditing")
                        .HasColumnType("bit");

                    b.Property<bool?>("allowFiltering")
                        .HasColumnType("bit");

                    b.Property<bool?>("allowFixing")
                        .HasColumnType("bit");

                    b.Property<bool?>("allowGrouping")
                        .HasColumnType("bit");

                    b.Property<bool?>("allowHeaderFiltering")
                        .HasColumnType("bit");

                    b.Property<bool?>("allowHiding")
                        .HasColumnType("bit");

                    b.Property<bool?>("allowSearch")
                        .HasColumnType("bit");

                    b.Property<bool?>("allowSorting")
                        .HasColumnType("bit");

                    b.Property<bool?>("autoExpandGroup")
                        .HasColumnType("bit");

                    b.Property<string>("caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<string>("caption_VN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(4);

                    b.Property<string>("column_child")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("cssClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<string>("dataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(5);

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("minWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("orderNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("table_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("visible")
                        .HasColumnType("bit");

                    b.Property<decimal?>("width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("SysGenRowTable", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.SystemDB.SysVoucherForm.SysVoucherFormColumn", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("disabled")
                        .HasColumnType("bit");

                    b.Property<bool?>("edit")
                        .HasColumnType("bit");

                    b.Property<string>("format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("groupId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("labelControl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("labelControlCN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("labelControlVN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("labelModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("labelRequired")
                        .HasColumnType("bit");

                    b.Property<string>("mask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maskRules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("number_order")
                        .HasColumnType("int");

                    b.Property<string>("placeholder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("readOnly")
                        .HasColumnType("bit");

                    b.Property<bool?>("required")
                        .HasColumnType("bit");

                    b.Property<bool?>("showClearButton")
                        .HasColumnType("bit");

                    b.Property<string>("table_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeControl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("visible")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("SysVoucherFormColumn", (string)null);
                });

            modelBuilder.Entity("DAL_QUANLI.Models.SystemDB.SysVoucherForm.SysVoucherFormGroup", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("create_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("create_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("group_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("number_order")
                        .HasColumnType("int");

                    b.Property<string>("table_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("update_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("SysVoucherFormGroup", (string)null);
                });

            modelBuilder.Entity("quan_li_app.Models.SystemDB.AppModule", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("dateEnable")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("enabled")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.ToTable("AppModels", (string)null);
                });

            modelBuilder.Entity("quan_li_app.Models.SystemDB.SysMenu", b =>
                {
                    b.Property<string>("menuid")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar")
                        .HasColumnName("menuid");

                    b.Property<string>("action1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("action2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("action3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("action4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("action5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("action6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("action7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("defaultActive")
                        .HasColumnType("bit");

                    b.Property<string>("icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isParent")
                        .HasColumnType("bit")
                        .HasColumnName("isParent");

                    b.Property<string>("menuIDParent")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar")
                        .HasColumnName("menuIDParent");

                    b.Property<string>("moduleApp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("name");

                    b.Property<string>("nameVN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("menuid");

                    b.ToTable("SysMenu", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
